apiVersion: v1
kind: Pod
metadata:
  name: configmapprodpod
spec:
  containers:
    - name: c1
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: v1
          mountPath: "/usr/share/nginx/html"    
  volumes:
    - name: v1
      configMap:
        name: configmapprodhtml    

