apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmapproddeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: prod
  template:
    metadata:
      name: configmapprodpod
      labels:
        tier: prod
    spec:
      containers:
        - name: c1
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: v1
              mountPath: "/usr/share/nginx/html"
      volumes:
        - name: v1
          configMap:
            name: configmapprodhtml
    

