apiVersion: v1
kind: Pod
metadata:
  name: emptydirpod
spec:
  containers:
    - name: c1
      image: centos
      command: ["/bin/sh", "-c", "echo container1; sleep 3600"]  
      volumeMounts:
        - mountPath: /demo1
          name: vol1  
    - name: c2
      image: ubuntu
      command: ["/bin/sh", "-c", "echo container2; sleep 3600"]
      volumeMounts: 
        - mountPath: /demo2
          name: vol1  
    - name: c3  
      image: alpine
      command: ["/bin/sh", "-c", "echo container3; sleep 3600"]
      volumeMounts:
        - mountPath: /demo3
          name: vol1  
  volumes:
    - name: vol1
      emptyDir: {}    

