apiVersion: batch/v1
kind: Job
metadata:
  name: jobpod
spec:
  completions: 4
  parallelism: 2
  completionMode: Indexed
  backoffLimit: 4
  template:
    metadata:
      name: coutdown
    spec:
      containers:
        - name: counter
          image: centos:7
          command:
            - "/bin/bash"
            - "-c"
            - "for i in 9 8 7 6 5 4 3 2 1; do echo $i; done"
      restartPolicy: Never


