apiVersion: v1
kind: Pod
metadata:
  name: pvpvcrwopod2
spec:
  nodeName: k8s-node1
  containers:
    - name: c1
      image: tomcat:8.5
      volumeMounts:
        - name: pvvol1
          mountPath: "/usr/local/tomcat/logs"
  volumes:
    - name: pvvol1
      persistentVolumeClaim:
        claimName: pvcrwo


