apiVersion: apps/v1
kind: ReplicaSet
metadata: 
 name: rs2
spec:
  replicas: 3
  selector:
    matchExpressions:
      - {key: tier, operator: In, values: [frontend, test, back]}
      - {key: env, operator: NotIn, values: [production]}
  template:
    metadata:
      labels:
        tier: frontend
        env: dev
    spec:
      containers:
        - name: apache
          image: httpd
          ports:
            - containerPort: 80

