apiVersion: v1
kind: Pod
metadata:
  name: secretopaquepod
spec:
  containers:
    - name: c1
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: vol1
          mountPath: /rajesh/secret    
          readOnly: true  
  volumes:
    - name: vol1
      secret:
        secretName: secretopaque    


