apiVersion: v1
kind: Secret
metadata:
  name: secretdotfile
data:
  .secret-file: dmFsdWUtMg0KDQo=
---
apiVersion: v1
kind: Pod
metadata:
  name: secretdotfilespod
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: secretdotfile
  containers:
    - name: dotfile-test-container
      image: nginx
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/rajesh/secret"
