apiVersion: v1
kind: Pod
metadata:
  name: secretgenericpod
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: secretgeneric
  containers:
    - name: container1
      image: nginx
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/rajesh/secret"
