apiVersion: v1
kind: Pod
metadata:
  name: secretbasicauthpod
spec:
  containers:
    - name: c1
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: vol1
          mountPath: "/rajesh/secret"
  volumes:
    - name: vol1
      secret:
        secretName: secretbasicauth    

