apiVersion: v1
kind: Service
metadata:
  name: cluster_svc
spec:
  selector:
    name: deployment
  type: ClusterIP
  ports:
   - port: 8001
     targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: node_svc
spec:
  selector:
    name: deployment
  type: NodePort
  ports:
   - port: 8002
     targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: headless_svc
spec:
  selector:
    name: deployment
  type: ClusterIP
  clusterIP: None  
  ports:
   - port: 8003
     targetPort: 80
