apiVersion: v1
kind: Pod
metadata:
  name: tolerationpod2
spec:
  containers:
    - name: c1
      image: busybox
      command: ["/bin/sh", "-c", "sleep 1000"]
  tolerations:
    - key: color
      operator: Equal
      value: green
      effect: NoSchedule    

