kind: Deployment
apiVersion: apps/v1
metadata:
  name: ubuntudep
spec:
  replicas: 4
  selector:
    matchLabels:
      name: deployment
  template:
    metadata:
      name: testpod1
      labels:
        name: deployment
    spec:
      containers:
        - name: c00
          image: ubuntu
          command: ["/bin/bash", "-c","while true; do echo hi i am teaching k8s; sleep 5; done"]
