apiVersion: v1
kind: Pod
metadata: 
  name: cmpod
spec:
  containers:
    - name: c1
      image: nginx
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: cmap1

