apiVersion: v1
kind: Pod
metadata: 
  name: initconpod
spec:
  containers:
    - name: c1
      image: nginx
      ports:
        - containerPort: 80
  initContainers:
    - name: init-c1
      image: busybox:1.28
      command: ["/bin/sh", "-c", "sleep 60"]    
    - name: init-c2
      image: busybox:1.28
      command: ["/bin/sh", "-c", "sleep 120"]    

