apiVersion: v1
kind: Pod
metadata:
  name: nodeaffinitypod2
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: diskType
            operator: In
            values:
            - flash     
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
