apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: nodeaffinitypod3
spec:
  containers:
  - image: nginx
    name: pod
    ports:
    - containerPort: 80
  affinity: 
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: network
            operator: In  
            values: 
            - fast
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference: 
          matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd

