apiVersion: v1
kind: Pod
metadata:
  name: secretpod
spec:
  containers:
    - name: c1
      image: nginx
      ports:
        - containerPort: 80
      envFrom:
        - secretRef:
            name: secret1    

