apiVersion: v1
kind: Pod
metadata:
  name: securitycontextpod
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  volumes:
  - name: v1
    emptyDir: {}
  containers:
  - name: c1
    image: busybox:1.28
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: v1
      mountPath: /data/demo
    securityContext:
      allowPrivilegeEscalation: false

